# use bearstech stretch
FROM bearstech/java:8

ENV SOLR_VERSION=3.5.0
ENV BUILD_DIR=build/$SOLR_VERSION/solr

RUN set -eux \
    # solr installation dir
    &&  mkdir -p /opt/solr/solr/ \
    # config dir /etc/solr/conf
    &&  mkdir -p /etc/solr/conf \
    &&  chmod 0777 /etc/solr -R \
    &&  ln -s /etc/solr/conf /opt/solr/solr/conf \
    # data dir /var/lib/solr/data
    &&  mkdir -p /var/lib/solr/data \
    &&  chmod 0777 /var/lib/solr -R \
    &&  ln -s /var/lib/solr/data /opt/solr/solr/data

# only take what we need from solr build directory
COPY $BUILD_DIR/etc/ /opt/solr/etc/
COPY $BUILD_DIR/lib/ /opt/solr/lib/
COPY $BUILD_DIR/webapps/ /opt/solr/webapps/
COPY $BUILD_DIR/contrib/ /opt/solr/contrib/
COPY $BUILD_DIR/dist/ /opt/solr/dist/
COPY $BUILD_DIR/start.jar /opt/solr/
COPY $BUILD_DIR/solr/solr.xml /opt/solr/solr/
COPY $BUILD_DIR/solr/conf/ /etc/solr/conf

# configure log4j to log only on console
COPY log4j.properties.jetty-8.1.10 /opt/solr/resources/log4j.properties

# Run Apache Solr
EXPOSE 8983
WORKDIR /opt/solr
ENV SOLR_TIMEZONE="Europe/Paris"



CMD ["/bin/bash", "-c", "java -server -Xms64m -Xmx512m -Djetty.port=8983 -Dsolr.solr.home=/opt/solr/solr -Dsolr.solr.data.dir=/var/lib/solr/data -jar start.jar"]

# generated labels

ARG GIT_VERSION
ARG GIT_DATE
ARG BUILD_DATE

LABEL \
    com.bearstech.image.revision_date=${GIT_DATE} \
    org.opencontainers.image.authors=Bearstech \
    org.opencontainers.image.revision=${GIT_VERSION} \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.url=https://github.com/factorysh/docker-solr \
    org.opencontainers.image.source=https://github.com/factorysh/docker-solr/blob/${GIT_VERSION}/Dockerfile.35
