# use bearstech stretch 
FROM bearstech/debian:stretch

ENV DEBIAN_FRONTEND noninteractive

# we need openjdk
RUN apt-get update && apt-get install -y \
  ca-certificates \
  sudo \
  vim-tiny \
  openjdk-8-jre-headless && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

ARG uid=1000

ENV SOLR_VERSION=3.6.2
ENV SOLR=apache-solr-$SOLR_VERSION
ADD http://archive.apache.org/dist/lucene/solr/$SOLR_VERSION/$SOLR.tgz /tmp/$SOLR.tgz

RUN \ 
    # create user
    useradd -m solr -d /opt/solr --uid ${uid} --shell /bin/bash && \
    # temp dir
    mkdir /tmp/solr && \
    # only extract example (contains solr + jetty)
    tar --strip-components=2 -C /tmp/solr -xzf /tmp/$SOLR.tgz $SOLR/example && \
    # only extract contrib (contains additionals solr libs)
    tar --strip-components=1 -C /tmp/solr -xzf /tmp/$SOLR.tgz $SOLR/contrib && \
    # config dir
    mkdir -p /opt/solr/solr/conf && \
    # data dir
    mkdir /var/lib/solr && \
    chown ${uid}.${uid} /var/lib/solr -R && \
    # only take what we need from example directory
    cp -R /tmp/solr/etc /tmp/solr/lib /tmp/solr/webapps /tmp/solr/contrib /tmp/solr/start.jar \
        /opt/solr && \
    cp /tmp/solr/solr/solr.xml /opt/solr/solr/ && \
    # remove tmp files
    rm -rf /tmp/solr /tmp/$SOLR.tgz && \
    chown ${uid}.${uid} /opt/solr -R

# Run Apache Solr
ENV SOLR_PORT=8983
EXPOSE $SOLR_PORT
WORKDIR /opt/solr
# run as solr user
USER solr
CMD ["/bin/bash", "-c", "java -jar start.jar","-Djetty.port=$SOLR_PORT"]
