# use bearstech stretch
FROM bearstech/debian:stretch

ENV DEBIAN_FRONTEND noninteractive

ENV SOLR_VERSION=4.9.1
ENV SOLR_PORT=8983

ENV BUILD_DIR=build/$SOLR_VERSION/solr

# we need openjdk
RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                    openjdk-8-jre-headless \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    # solr installation dir
    &&  mkdir -p /opt/solr/solr/collection1/ \
    # config dir /etc/solr/conf
    &&  mkdir -p /etc/solr/conf \
    &&  chmod 0777 /etc/solr -R \
    &&  ln -s /etc/solr/conf /opt/solr/solr/collection1/conf \
    # data dir /var/lib/solr/data
    &&  mkdir -p /var/lib/solr/data \
    &&  chmod 0777 /var/lib/solr -R \
    &&  ln -s /var/lib/solr/data /opt/solr/solr/collection1/data

# only take what we need from example directory
COPY $BUILD_DIR/etc/ /opt/solr/etc/
COPY $BUILD_DIR/lib/ /opt/solr/lib/
COPY $BUILD_DIR/webapps/ /opt/solr/webapps/
COPY $BUILD_DIR/contrib/ /opt/solr/contrib/
COPY $BUILD_DIR/start.jar /opt/solr/
COPY $BUILD_DIR/contexts/ /opt/solr/contexts/
COPY $BUILD_DIR/solr/solr.xml /opt/solr/solr/
COPY $BUILD_DIR/solr/collection1/core.properties /opt/solr/solr/collection1/
COPY $BUILD_DIR/solr/collection1/conf /etc/solr/conf

# configure log4j to log only on console
COPY log4j.properties.jetty-8.1.10 /opt/solr/resources/log4j.properties

# Run Apache Solr
EXPOSE $SOLR_PORT
WORKDIR /opt/solr

CMD ["/bin/bash", "-c", "java -jar start.jar","-Djetty.port=$SOLR_PORT"]
