# use bearstech stretch
FROM bearstech/debian:stretch

ENV DEBIAN_FRONTEND noninteractive

ENV SOLR_VERSION=4.9.1
ENV SOLR_PORT=8983

ENV BUILD_DIR=build/$SOLR_VERSION/solr

# we need openjdk
RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                    openjdk-8-jre-headless \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
        # config dir
    &&  mkdir -p /opt/solr/solr/collection1/conf \
        # data dir
    &&  mkdir /var/lib/solr

# only take what we need from example directory
COPY $BUILD_DIR/etc/ /opt/solr/etc/
COPY $BUILD_DIR/lib/ /opt/solr/lib/
COPY $BUILD_DIR/webapps/ /opt/solr/webapps/
COPY $BUILD_DIR/contrib/ /opt/solr/contrib/
COPY $BUILD_DIR/start.jar /opt/solr/
COPY $BUILD_DIR/contexts/ /opt/solr/contexts/
COPY $BUILD_DIR/solr/solr.xml /opt/solr/solr/
COPY $BUILD_DIR/solr/collection1/ /opt/solr/solr/collection1/

# configure log4j
COPY log4j.properties.jetty-8.1.10 /opt/solr/resources/log4j.properties

# Run Apache Solr
EXPOSE $SOLR_PORT
WORKDIR /opt/solr

CMD ["/bin/bash", "-c", "java -jar start.jar","-Djetty.port=$SOLR_PORT"]
