# use bearstech java
FROM bearstech/java:11

ENV SOLR_VERSION=8.11.1

ENV BUILD_DIR=build/$SOLR_VERSION/solr

# we need openjdk
RUN set -eux \
    # solr installation dir
    &&  mkdir -p /opt/solr \
    # config dir /etc/solr/conf
    &&  mkdir -p /etc/solr/conf \
    &&  chmod 0777 /etc/solr/conf \
    # data dir /var/lib/solr/data
    &&  mkdir -p /var/lib/solr/data/ \
    &&  chmod 0777 /var/lib/solr/data

# install to /opt/solr
COPY $BUILD_DIR /opt/solr/
RUN mkdir /opt/solr/server/solr/core1
RUN chmod 0777 /opt/solr/server/solr/core1
RUN cp -r /opt/solr/server/solr/configsets/_default/conf/* /etc/solr/conf
RUN  echo "name=core1" > /opt/solr/server/solr/core1/core.properties
RUN ln -s /etc/solr/conf /opt/solr/server/solr/core1/conf

# configure log4j to log only on console
COPY log4j.properties.solr /opt/solr/server/resources/log4j.properties
COPY log4j2.xml /opt/solr/server/resources/log4j2.xml

# Run Apache Solr
EXPOSE 8983
WORKDIR /opt/solr/server
ENV SOLR_TIMEZONE="Europe/Paris"
ENV SOLR_JAVA_MEM="-Xms512m -Xmx512m"

CMD ["/bin/bash", "-c", "java -server $SOLR_JAVA_MEM -XX:+UseG1GC -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=250 -XX:+AlwaysPreTouch -XX:+ExplicitGCInvokesConcurrent -Djetty.port=8983 -Duser.timezone=$SOLR_TIMEZONE -XX:-OmitStackTraceInFastThrow -Djetty.home=/opt/solr/server -Dsolr.data.dir=/var/lib/solr/data -Dsolr.install.dir=/opt/solr -Dlog4j2.formatMsgNoLookups=true -Xss256k -jar start.jar --module=http --module=gzip"]

# generated labels

ARG GIT_VERSION
ARG GIT_DATE
ARG BUILD_DATE

LABEL \
    com.bearstech.image.revision_date=${GIT_DATE} \
    org.opencontainers.image.authors=Bearstech \
    org.opencontainers.image.revision=${GIT_VERSION} \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.url=https://github.com/factorysh/docker-solr \
    org.opencontainers.image.source=https://github.com/factorysh/docker-solr/blob/${GIT_VERSION}/Dockerfile.8
