# use bearstech stretch
FROM bearstech/debian:stretch

ENV DEBIAN_FRONTEND noninteractive

# we need openjdk
RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                    openjdk-8-jre-headless \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/*

ENV SOLR_VERSION=6.6.5

ENV BUILD_DIR=build/$SOLR_VERSION/solr

# we need openjdk
RUN set -eux \
    # solr installation dir
    &&  mkdir -p /opt/solr \
    # config dir /etc/solr/conf
    &&  mkdir -p /etc/solr/conf \
    &&  chmod 0777 /etc/solr -R \
    # data dir /var/lib/solr/data
    &&  mkdir -p /var/lib/solr/data/ \
    &&  chmod 0777 /var/lib/solr -R

# install to /opt/solr
COPY $BUILD_DIR /opt/solr/
RUN mkdir /opt/solr/server/solr/core1
RUN chmod 0777 /opt/solr/server/solr/core1
RUN cp -r /opt/solr/server/solr/configsets/data_driven_schema_configs/conf/* /etc/solr/conf
RUN  echo "name=core1" > /opt/solr/server/solr/core1/core.properties
RUN ln -s /etc/solr/conf /opt/solr/server/solr/core1/conf

# configure log4j to log only on console
COPY log4j.properties.solr /opt/solr/server/resources/log4j.properties

# Run Apache Solr
EXPOSE 8983
WORKDIR /opt/solr/server
ENV SOLR_TIMEZONE="Europe/Paris"

ARG GIT_VERSION
LABEL com.bearstech.source.solr=https://github.com/factorysh/docker-solr/commit/${GIT_VERSION}

CMD ["/bin/bash", "-c", "java -server -Xms512m -Xmx512m -XX:NewRatio=3 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ConcGCThreads=4 -XX:ParallelGCThreads=4 -XX:+CMSScavengeBeforeRemark -XX:PretenureSizeThreshold=64m -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=50 -XX:CMSMaxAbortablePrecleanTime=6000 -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:-OmitStackTraceInFastThrow -Djetty.port=8983 -Duser.timezone=$SOLR_TIMEZONE -Djetty.home=/opt/solr/server -Dsolr.data.dir=/var/lib/solr/data -Dsolr.install.dir=/opt/solr -Xss256k -jar start.jar --module=http"]
