# use bearstech stretch
FROM bearstech/debian:stretch

ENV DEBIAN_FRONTEND noninteractive

ENV SOLR_VERSION=3.5.0
ENV JETTY_VERSION=8.1.10

ENV BUILD_DIR_SORL=build/$SOLR_VERSION/solr
ENV BUILD_DIR_JETTY=build/jetty-$JETTY_VERSION/jetty

# we need openjdk
RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
                    openjdk-8-jre-headless \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/* \
    # solr installation dir
    &&  mkdir -p /opt/solr/solr/ \
    # config dir /etc/solr/conf
    &&  mkdir -p /etc/solr/conf \
    &&  chmod 0777 /etc/solr -R \
    &&  ln -s /etc/solr/conf /opt/solr/solr/conf \
    # data dir /var/lib/solr/data
    &&  mkdir -p /var/lib/solr/data \
    &&  chmod 0777 /var/lib/solr -R \
    &&  ln -s /var/lib/solr/data /opt/solr/solr/data

# only take what we need from solr build directory
COPY $BUILD_DIR_SORL/webapps/ /opt/solr/webapps/
COPY $BUILD_DIR_SORL/contrib/ /opt/solr/contrib/
COPY $BUILD_DIR_SORL/solr/solr.xml /opt/solr/solr/
COPY $BUILD_DIR_SORL/solr/conf/ /etc/solr/conf

# get jetty
COPY $BUILD_DIR_JETTY/start.jar /opt/solr/
COPY $BUILD_DIR_JETTY/etc/ /opt/solr/etc/
COPY $BUILD_DIR_JETTY/lib/ /opt/solr/lib/
COPY $BUILD_DIR_JETTY/contexts/ /opt/solr/contexts/
COPY log4j.properties.jetty-8.1.10 /opt/solr/resources/log4j.properties

# Run Apache Solr
EXPOSE 8983
WORKDIR /opt/solr
ENV SOLR_TIMEZONE="Europe/Paris"
CMD ["/bin/bash", "-c", "java -jar start.jar", "-Djetty.port=8983", "-Dsolr.solr.home=/opt/solr/solr", "-Dsolr.solr.data.dir=/var/lib/solr/data"]
