ARG solr_version=latest
ARG solr_full_version=latest

# use bearstech solr
FROM bearstech/solr:${solr_version}

# add user solr
ARG uid=1001
RUN useradd solr -d /opt/solr --uid ${uid} --shell /bin/bash

# Remove default configuration files
# RUN rm -rf /etc/solr/conf/*
# Copy my configuration files
# COPY /conf/solr /etc/solr/conf

# Adjust owner
RUN chown ${uid}.${uid} /opt/solr -R
RUN chown ${uid}.${uid} /var/lib/solr -R
RUN chown ${uid}.${uid} /etc/solr -R

USER solr
