---

version: '3'
services:
    solr:
        image: bearstech/solr:latest
        ports:
            - '8983:8983'

    goss:
        image: bearstech/debian:stretch
        command: "sleep 600000000000000000000000"
        volumes:
            - ../bin/goss:/usr/bin/goss
            - ../tests_solr:/goss
        working_dir: /goss
        links:
            - solr
