---

version: '3'
services:
    solr:
        image: bearstech/solr:${SOLR_VERSION}
        ports:
            - '8983:8983'

    client:
        image: bearstech/debian:stretch
        command: >
            goss -g solr.yaml validate
                --retry-timeout 30s
                --sleep 1s
                --max-concurrent 4
                --format documentation
        volumes:
            - ../bin/goss:/usr/bin/goss
            - ../tests_solr:/goss
        working_dir: /goss
        links:
            - solr
