---

version: '3'

services:
    solr:
        image: tests/solr:${SOLR_VERSION:-latest}
        build:
            context: .
            dockerfile: Dockerfile.solr
        ports:
            - '8983:8983'
        volumes:
            - ./test_tmp:/var/lib/solr/data

    client:
        environment:
            BASE_URL: ${BASE_URL:-/solr/core1/}
            SOLR_VERSION: ${SOLR_VERSION}
        image: bearstech/debian:stretch
        command: >
            goss -g solr.yaml validate
                --retry-timeout 30s
                --sleep 1s
                --max-concurrent 4
                --format documentation
        volumes:
            - ../bin/goss:/usr/bin/goss
            - ../tests_solr:/goss
            - ./test_tmp:/var/lib/solr/data
        working_dir: /goss
        links:
            - solr
